#' Get timestamps for beginning and end of events
#'
#' @param eventData a dataframe generated by removeEventRows containing all event data
#' @param firstEvent a string defining the first event of interest in the recording
#' @param firstInd an integer marking which occurrence of the event type should be set as the first. Default 1 sets the first occurance.
#' @param lastEvent a string defining the last event of interest in the recording
#' @param lastInd an integer marking which occurrence of the event type should be set as the first. Default 1 sets the first occurance.
#' @param ... additional arguments are of either the form value or tag = value. Component names are created based on the tag (if present) or the deparsed argument itself.
#'
#' @importFrom purrr detect_index
#' @importFrom stringr str_detect
#' @return list containing start and end times
#' @export
#'
getEventTimes <-
  function(eventData,
           firstEvent,
           firstInd = 1,
           lastEvent,
           lastInd = NULL,
           ...) {
    startTime <-
      eventData$recordingTimestamp_ms[which(eventData$event == firstEvent)[firstInd]]
    endInds <- which(eventData$event == lastEvent)
    if (isempty(lastInd) && !isempty(endInds)) {
      lastInd <- length(endInds)
    } else if (isempty(endInds)) {
      lastInd <- NA
    }
    endTime <- eventData$recordingTimestamp_ms[endInds[lastInd]]

    if (is.na(startTime)) {
      print(paste0("First event ", firstEvent, " does not exist."))
    }
    if (is.na(endTime)) {
      print(paste0("Last event ", lastEvent, " does not exist."))
    }
    return(c(startTime, endTime))
  }
